### ISSUE TITLE
Pattern 2.6 not Python 3 compatible

### ISSUE THREAD

**Issue by encolpe** [biodigitals/apetizer#8]
Hello

I got this error when installing with Python 3. and Django 1.8:

```bash
Downloading/unpacking pattern (from -r requirements.txt (line 6))
  Downloading pattern-2.6.zip (24.6MB): 24.6MB downloaded
  Running setup.py (path:/tmp/pip-build-c80fr52l/pattern/setup.py) egg_info for package pattern
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-c80fr52l/pattern/setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-c80fr52l/pattern/setup.py", line 40

    print n

          ^

SyntaxError: Missing parentheses in call to 'print'
```

**Comment by encolpe** [comment]
I've push the bug report to owner:
https://github.com/clips/pattern/issues/140
